### ISSUE TITLE
🐛 [BUG/ERROR] App crash due to issues related to network

### ISSUE THREAD

**Issue by hrmoh** [tapsellorg/TapsellPlusSDK-FlutterPlugin#14]
Whenever there are issues with the device internet connectivity (no connection / VPN usage), app crashes and aborts with the message pasted below.

java.lang.IllegalStateException: Reply already submitted
	at q3.c$g.a(DartMessenger.java:4)
	at b4.l$a$a.a(MethodChannel.java:1)
	at ir.tapsell.plus.flutter.TapsellMethodCallHandler$1.error(Unknown Source:5)
	at s5.j.R(Unknown Source:4)
	at s5.j.c(Unknown Source:0)
	at s5.c.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MortezaNedaei** [comment]
I'm closing this. feel free to reopen if you think the issue still exists
