### ISSUE TITLE
🐛 [BUG/ERROR] tapsell plus will be crash after request for banner ads

### ISSUE THREAD

**Issue by saiedfsd** [tapsellorg/TapsellPlusSDK-FlutterPlugin#15]
**Describe the issue**:
tapsell plus v 2.1.7 is not compatible with new versions of most commonly used libraries in flutter because of new gradle and  kotlin version

everything is ok befor request for banner ads, after that request application will be crash in almost after 15 seconds and completely exit from app.

**Paste the error text in your logs**:
Shutting down VM
FATAL EXCEPTION: main
java.lang.IllegalStateException: Reply already submitted
	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
	at ir.tapsell.plus.flutter.TapsellMethodCallHandler$1.response(Unknown Source:6)
	at ir.tapsell.plus.q.c.c(Unknown Source:24)
	at ir.tapsell.plus.q.c.lambda$SPmpZHA1y-dix0kyIsf5YXViZVE(Unknown Source:0)
	at ir.tapsell.plus.q.-$$Lambda$c$SPmpZHA1y-dix0kyIsf5YXViZVE.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**[Optionally paste the whole stacktrace for more details**:

**How to reproduce this issue:**
flutter : environment:
  sdk: '>=2.18.4 <3.0.0'
  
tapsell_plus: ^2.1.7
multiDexEnabled true
ext.kotlin_version = '1.7.10'
classpath 'com.android.tools.build:gradle:4.1.3'
gradle-wrapper distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip

and using common and widely used libraries in Flutter as hive, path_provider, flutter_bloc, equatable, provider, async etc.

**App package name**: ``
It doesn't matter in any of the used projects, this issue happens.

**Comment by mahdiqdi** [comment]
من هم مشکل مشابه شمارو دارم
بنر نمایش داده میشه بعد که روش کلیک میکنم وارد اون تبلیغ که میشه اپ کرش میکنه

**Comment by MortezaNedaei** [comment]
Fixed in [2.2.3](https://github.com/tapsellorg/TapsellPlusSDK-FlutterPlugin/releases/tag/v2.2.3).
Please check and confirm.
Thanks

**Comment by saiedfsd** [comment]
Version 2.2.3 of Tapsel Plus library was tested.
The problem reported in this issue has been resolved.
thank you.
